# Numpy(Numerical Python)

In [4]:
a=[1,2,3,4,5]
print(a)
type(a)

[1, 2, 3, 4, 5]


list

In [7]:
import numpy as np

In [18]:
np.version

<module 'numpy.version' from 'C:\\Users\\vasan\\anaconda3\\lib\\site-packages\\numpy\\version.py'>

#ndarray

In [23]:
a=[1,2,3,4,5]

np_a=np.array(a)
print(np_a)
type(np_a)

[1 2 3 4 5]


numpy.ndarray

In [25]:
np_a

array([1, 2, 3, 4, 5])

#Creating Numpy Arrays

#0-D

In [30]:
arr=np.array(42)
print(arr)
type(arr)

42


numpy.ndarray

#1-D

In [34]:
a=np.array([0,1,2,3])
print(a)

[0 1 2 3]


In [36]:
a=np.array([2,3,4,5])
print(a)

[2 3 4 5]


In [38]:
#Print Dimension

In [40]:
a.ndim

1

In [42]:
#Shape

In [44]:
a.shape

(4,)

In [46]:
#Functions for creating Arrays

In [48]:
#Arrange

In [51]:
a=np.arange(10,101,10)
print(a)

[ 10  20  30  40  50  60  70  80  90 100]


In [54]:
#linspace return evenly spaced numbers

In [56]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [58]:
#Zeros

In [60]:
np.zeros(3)

array([0., 0., 0.])

In [62]:
np.ones(2)

array([1., 1.])

In [64]:
#random.randint

In [66]:
np.random.randint(1,41,5)

array([39,  1,  1, 36, 40])

# Accessing elements

In [70]:
#1.Accesing a single value through indexing

In [72]:
a=np.arange(10,101,10)
print(a)

a[2]

[ 10  20  30  40  50  60  70  80  90 100]


30

In [76]:
#2.Accesing a multiple value based on slicing

In [77]:
a[1:8:2]

array([20, 40, 60, 80])

In [78]:
#3.Accesing a multiple value based on indexing

In [80]:
a[[0,4,4,5,7]]

array([10, 50, 50, 60, 80])

In [82]:
#3.Accesing a multiple value based on condition(Mask indexing or Fancy Indexing)

In [84]:
a%2==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [85]:
a[a%2==0]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

# Numpy is Mutable

In [90]:
#Replace
#Add
#Remove

In [92]:
a[5]=50
print(a)

[ 10  20  30  40  50  50  70  80  90 100]


In [94]:
#Replace
a[[1,5]]=80
a

array([ 10,  80,  30,  40,  50,  80,  70,  80,  90, 100])

In [96]:
#Add
b=np.append(a,[110,120])
b

array([ 10,  80,  30,  40,  50,  80,  70,  80,  90, 100, 110, 120])

In [98]:
#Remove a single value in a array
b=np.delete(a,8)
print(a)

[ 10  80  30  40  50  80  70  80  90 100]


In [100]:
#Remove a multiple value in a array
b=np.delete(a,[1,2])
print(b)

[ 10  40  50  80  70  80  90 100]


In [102]:
#Sort

In [105]:
np.sort([4,6,8,2,1])

array([1, 2, 4, 6, 8])

In [107]:
#Copy Array

In [109]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [111]:
#around()

In [113]:
arr=np.array([1.432,3.087,4.56])
np.around(arr)

array([1., 3., 5.])

In [115]:
np.around(arr,2)

array([1.43, 3.09, 4.56])

# Operations

In [121]:
#Arthmetic operations

In [123]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [125]:
a+1

array([2, 3, 4, 5])

In [127]:
a**2

array([ 1,  4,  9, 16])

In [128]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([1,2,3,4])
print(a)
print(b)
print(c)

[1 2 3 4]
[5 6 7 8]
[1 2 3 4]


In [130]:
a+b

array([ 6,  8, 10, 12])

In [132]:
a-b

array([-4, -4, -4, -4])

In [134]:
a*b

array([ 5, 12, 21, 32])

In [136]:
a==b

array([False, False, False, False])

In [138]:
a>b

array([False, False, False, False])

In [142]:
np.array_equal(a,b)

False

In [143]:
np.array_equal(a,c)

True

In [145]:
#Mathematical Operations

In [147]:
a=np.arange(0,6)
a

array([0, 1, 2, 3, 4, 5])

In [151]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [152]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219])

In [154]:
np.log(a)

C:\Users\vasan\AppData\Local\Temp\ipykernel_13236\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791])

In [156]:
np.exp(a)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [158]:
#Statistical Operations

In [160]:
np.mean(a)

2.5

In [162]:
np.median(a)

2.5

In [164]:
np.std(a)

1.707825127659933

# 2D Numpy Array

In [167]:
b=np.array([[0,1,2],[3,4,5]])
print(b)

[[0 1 2]
 [3 4 5]]


In [169]:
b.ndim

2

In [171]:
b.shape

(2, 3)

In [179]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [175]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [177]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [180]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [182]:
a=np.array([[10,20],[30,40]])
print(a)
print(a[1,1])

[[10 20]
 [30 40]]
40


In [184]:
#assigning vlaue in 2D Array
a[1,1]=25
a

array([[10, 20],
       [30, 25]])

In [186]:
#Flattening : Converting Nd array to 1D Array

In [189]:
a=np.array([[0,1,2],[3,4,5]])
a.ravel()

array([0, 1, 2, 3, 4, 5])

In [191]:
#Reshape array

In [194]:
arr=np.arange(6)
print(arr)
print(arr.shape)

[0 1 2 3 4 5]
(6,)


In [196]:
a1=arr.reshape(2,3)
a1

array([[0, 1, 2],
       [3, 4, 5]])

In [198]:
#Transpose array

In [200]:
c=a.T
print(c)

[[0 3]
 [1 4]
 [2 5]]


In [202]:
#sort

In [204]:
#Sorting along an axis: axis=1----->row and axis=0----->colums
a=np.array([[5,4,6],[2,8,2]])
b=np.sort(a,axis=0)
b

array([[2, 4, 2],
       [5, 8, 6]])

In [206]:
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[4,4],[4,4],[4,4]])

print(a+b)

[[ 5  6]
 [ 7  8]
 [ 9 10]]


In [208]:
print(a*b)

[[ 4  8]
 [12 16]
 [20 24]]


In [210]:
#Matrix multiplication

In [211]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.matmul(a,b)

array([[19, 22],
       [43, 50]])